//
//  MainPresenter.swift
//  CleanWeahter
//
//  Created by Seokho on 2020/10/26.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
	func showErrorAlert(errorResponse: Main.MainError.Response)
}

class MainPresenter: MainPresentationLogic {

	weak var viewController: MainDisplayLogic?
	
	func showErrorAlert(errorResponse: Main.MainError.Response) {
		
		let viewModel = Main.MainError.ViewModel(localError: errorResponse.error.localizedDescription)
		viewController?.showErrorAlert(errorViewModel: viewModel)
		
	}
	
}
