//
//  MainModels.swift
//  CleanWeahter
//
//  Created by Seokho on 2020/10/26.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreLocation
import UIKit

enum Main {
	
	enum FetchWeather {
		
		struct Request {
			let unit: String
		}
		
		struct Response {
			let weather: Weather?
            let error: Error?
            
            init(weather: Weather? = nil, error: Error? = nil) {
                self.weather = weather
                self.error = error
            }
		}
		
		struct ViewModel {
			let weather: Weather?
            let error: Error?
            
            init(weather: Weather? = nil, error: Error? = nil) {
                self.weather = weather
                self.error = error
            }
		}
	}

	
}
