//
//  MainModels.swift
//  CleanWeahter
//
//  Created by Seokho on 2020/10/26.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreLocation
import UIKit

enum Main {
	
	enum FetchWeather {
		
		struct Request {
			let unit: String
		}
		
		struct Response {
			let weather: Weather
		}
		
		struct ViewModel {
			let weather: Weather
		}
	}
	
	enum MainError {
		struct Request { }
		struct Response {
			let error: Error
		}
		
		struct ViewModel {
			let localError: String
		}
	}
	
}
