//
//  MainWorker.swift
//  CleanWeahter
//
//  Created by Seokho on 2020/10/26.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import CoreLocation
import UIKit

import RxSwift

protocol MainWorkerNetworking {
	func fetchData(request: Main.FetchWeather.Request) -> Observable<Weather>
}
class MainWorker: MainWorkerNetworking {
	
	let mainRepository: MainRepository
	
	init(mainRepository: MainRepository = MainRepository()) {
		self.mainRepository = mainRepository
	}
	
	func fetchData(request: Main.FetchWeather.Request) -> Observable<Weather> {
		print("CALL")
		return self.mainRepository.network.request(WeatherAPI.forecast(location: request.location, unit: request.unit))
			.map { try JSONDecoder().decode(Weather.self, from: $0.data) }
			.asObservable()

	}

}
